def C():
    print("     ########  ")
    print("   ##        # ")
    print("  #          # ")
    print(" ##            ")
    print(" #             ")
    print(" ##            ")
    print("   #         # ")
    print("    ##     #   ")
    print("      #####    ")
C()