def D():
    print(" ########      ")
    print(" ##      ##    ")
    print(" ##       ##   ")
    print(" ##        ##  ")
    print(" ##         ## ")
    print(" ##        ##  ")
    print(" ##       ##   ")
    print(" ##      ##    ")
    print(" ########      ")
D()