def E():
    print("   #########   ")
    print("   ##          ")
    print("   ##          ")
    print("   ##          ")
    print("   #########   ")
    print("   ##          ")
    print("   ##          ")
    print("   ##          ")
    print("   #########   ")
E()