def F():
    print("   #########   ")
    print("   #           ")
    print("   #           ")
    print("   #           ")
    print("   #########   ")
    print("   #           ")
    print("   #           ")
    print("   #           ")
    print("   #           ")
F()