def G():
    print("    #########  ")
    print("  ##         ##")
    print("  #           #")
    print(" ##           ")
    print("#             ")
    print(" ##      ######")
    print("  #           #")
    print("  ##          #")
    print("    ###########")
G()