def H():
    print("  ##       ##  ")
    print("  ##       ##  ")
    print("  ##       ##  ")
    print("  ##       ##  ")
    print("  ###########  ")
    print("  ##       ##  ")
    print("  ##       ##  ")
    print("  ##       ##  ")
    print("  ##       ##  ")
H()